"""Compile every node-group definition in nodes/ into primitives.blend.

Each *_node_group() function is generated by node2python and takes a
`node_tree_names` dict mapping builder-function -> already-built tree name,
which it indexes to look up dependencies it nests via Group nodes. NodeTreeNames
below resolves those lookups lazily: the first time a builder is referenced,
it gets built on the spot (recursively building its own dependencies first),
then memoized. This means node-definition files can be dropped in and their
builders discovered/invoked in any order, with no manual sequencing here and
no changes required to the generated files themselves.

Run with Blender's own Python interpreter, e.g.:
    blender --background --python build.py
"""
import importlib.util
import sys
import typing
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
NODES_DIR = HERE / "nodes"
OUTPUT_BLEND = HERE.parent / "procedural_skins_addon" / "assets" / "primitives.blend"
BUILDER_SUFFIX = "_node_group"
SKIP_FILES = {"build.py"}

# Node groups to expose as assets in Blender's Asset Browser, keyed by their
# tree name. catalog_id values are from
# procedural_skins_addon/assets/blender_assets.cats.txt.
ASSET_MARKS = {
    "Dermis Layer": "2dbdbc8f-4717-4c38-aaa6-4cdaaffea416",  # GenTact Toolbox/Layer Primitives
    "Sample Points": "2dbdbc8f-4717-4c38-aaa6-4cdaaffea416",  # GenTact Toolbox/Layer Primitives
    "Custom Sensor Layer": "2dbdbc8f-4717-4c38-aaa6-4cdaaffea416",  # GenTact Toolbox/Layer Primitives
    "Self-Cap Layer": "2dbdbc8f-4717-4c38-aaa6-4cdaaffea416",  # GenTact Toolbox/Layer Primitives
    "Wiring Layer": "2dbdbc8f-4717-4c38-aaa6-4cdaaffea416",  # GenTact Toolbox/Layer Primitives
}

# Asset Browser icons, keyed by tree name, loaded from resources/ since
# node-group previews aren't preserved across a from-scratch rebuild.
RESOURCES_DIR = HERE.parent / "resources"
ASSET_ICONS = {
    "Dermis Layer": RESOURCES_DIR / "dermis_splash.png",
    "Sample Points": RESOURCES_DIR / "sampling_splash.png",
    "Custom Sensor Layer": RESOURCES_DIR / "custom_sensor_splash.png",
    "Self-Cap Layer": RESOURCES_DIR / "sensors_splash.png",
    "Wiring Layer": RESOURCES_DIR / "wires_splash.png",
}


class NodeTreeNames(dict):
    """Lazily builds node groups on first reference, resolving dependencies
    depth-first so builders can be invoked in any order."""

    def __init__(self):
        super().__init__()
        self._building: set[typing.Callable] = set()

    def __missing__(self, builder: typing.Callable) -> str:
        if builder in self._building:
            chain = " -> ".join(f.__name__ for f in self._building)
            raise RecursionError(f"Circular node group dependency: {chain} -> {builder.__name__}")
        self._building.add(builder)
        try:
            tree = builder(self)
        finally:
            self._building.discard(builder)
        self[builder] = tree.name
        return tree.name


def discover_builders() -> list[typing.Callable]:
    """Import every node-definition module in nodes/ and collect its
    *_node_group() builder functions, in file/definition order."""
    builders = []
    for path in sorted(NODES_DIR.glob("*.py")):
        if path.name in SKIP_FILES:
            continue
        spec = importlib.util.spec_from_file_location(path.stem, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        for name, obj in vars(module).items():
            if name.endswith(BUILDER_SUFFIX) and callable(obj):
                builders.append(obj)
    return builders


def main():
    # Start from an empty scene so the output only contains generated node groups.
    bpy.ops.wm.read_factory_settings(use_empty=True)

    node_tree_names = NodeTreeNames()
    for builder in discover_builders():
        node_tree_names[builder]  # builds this group (and any unbuilt dependencies) if needed

    # Fake-user every group so groups with no other users (e.g. top-level
    # groups nothing else nests) aren't purged as orphans on save.
    for node_group in bpy.data.node_groups:
        node_group.use_fake_user = True

    for node_group in bpy.data.node_groups:
        catalog_id = ASSET_MARKS.get(node_group.name)
        if catalog_id:
            node_group.asset_mark()
            node_group.asset_data.catalog_id = catalog_id
            icon_path = ASSET_ICONS.get(node_group.name)
            if icon_path:
                with bpy.context.temp_override(id=node_group):
                    bpy.ops.ed.lib_id_load_custom_preview(filepath=str(icon_path))

    bpy.ops.wm.save_as_mainfile(filepath=str(OUTPUT_BLEND))
    print(f"Saved {OUTPUT_BLEND} with {len(bpy.data.node_groups)} node group(s)")


if __name__ == "__main__":
    main()
